baseurl = "http://example.org"
title = "Absolute beginner"
author = "MarcusE1W"
canonifyurls = true
paginate = 30
theme = "aether"

[params]
brand = "absolute beginner"
description = "aether Hugo theme for blogs"
bgimg = "flower-bg.jpg"
homeimg = "sky.jpg"