baseurl = "https://absolute-beginner.netlify.com"
title = "The Absolute Beginner"
author = "Marcus"
paginate = 20
# theme = "hugo-theme-minos"
# theme = "hugo-natrium-theme"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
pygmentsUseClassic=true
enableRobotsTXT = true

