baseURL = "https://gohugo.io/"
author = "MarcusE1W"
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# Above are configs from hugoBasicExample

title = "Absolute Beginner"
theme = "hugo-primer"
hasCJKLanguage = false
summaryLength = 70
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = ""
disqusShortname=""
copyright = "&copy;Qiushi Pan 2018-2019"

[params]
description = "Hugo-Primer theme's example site"
twitter = ""
useIcon = false
useTwitterCard = false
# exampleSite must not have js share widget: #36
# shareTo = ["Twitter", "Hatena", "Facebook", "Pocket"]
shareTo = []
showFooterCredits = false
math = true
